name: GeyserExtras_CN
version: '1.21.0-v1.1.4(cn1.0.2)'
author: "LetsGoAway"
main: dev.letsgoaway.geyserextras.spigot.GeyserExtras
api-version: '1.21'
softdepend: [floodgate, Geyser-Spigot]
commands:
  geyserextras:
    description: 打开GeyserExtras菜单。
    usage: /<command>
    permission: geyserextras.menu
    aliases:
      - ge
  platformlist:
    description: 显示包含所有玩家平台的列表。
    usage: /<command>
    permission: geyserextras.platformlist
    aliases:
      - pl
      - platforms
  playerlist:
    description: 显示Bedrock版玩家的Java版Tab玩家列表菜单。
    usage: /<command>
    permission: geyserextras.playerlist
    aliases:
      - l
      - players
      - listplayers
      - tab
      - tablist
  emotechat:
    description: 切换Java玩家对Bedrock玩家的表情聊天。
    usage: /<command>
    permission: geyserextras.emotechat
    aliases:
      - muteemotechat
permissions:
  geyserextras.menu:
    default: true
    description: 允许玩家执行/geyserextras命令
  geyserextras.platformlist:
    default: true
    description: 允许玩家执行/platformlist命令
  geyserextras.playerlist:
    default: true
    description: 允许玩家执行/playerlist命令
  geyserextras.emotechat:
    default: true
    description: 允许玩家执行/emotechat命令
